import {
  AcApDocManager,
  acapRunDatabaseEdit,
  AcDbDocumentEventArgs} from '@mlightcad/cad-simple-viewer'
import {
  AcCmColor,
  AcDbDatabase,
  AcDbLayerEventArgs,
  AcDbLayerModifiedEventArgs,
  AcDbLayerTableRecord,
  AcDbSysVarEventArgs,
  AcDbSysVarManager
} from '@mlightcad/data-model'
import { computed, onScopeDispose, reactive, ref } from 'vue'

export interface LayerInfo {
  name: string
  /**
   * Color string generated by AcCmColor.toString()
   */
  color: string
  cssColor: string
  isLocked: boolean
  isFrozen: boolean
  isInUse: boolean
  isOn: boolean
  isPlottable: boolean
  transparency: string
  linetype: string
  lineWeight: number
}

export type LayerStateToggleKey = 'on' | 'frozen' | 'locked'

export interface LayerStateSnapshot {
  clayer: string
  states: LayerInfo[]
}

export function useLayers(editor: AcApDocManager) {
  const layerFrozenFlag = 0x01
  const layerLockedFlag = 0x04
  const layerEditLabel = 'Layer'
  const reactiveLayers = reactive<LayerInfo[]>([])
  const currentLayerNameState = ref('')
  let observedDatabase: AcDbDatabase | undefined

  const getCurrentDatabase = () => editor.curDocument?.database
  const syncCurrentLayerName = (db = getCurrentDatabase()) => {
    currentLayerNameState.value = db?.clayer || ''
  }

  const openLayerForWrite = (
    db: AcDbDatabase,
    layerName: string
  ): AcDbLayerTableRecord | undefined => {
    const layer = db.tables.layerTable.getAt(layerName)
    if (!layer) return undefined
    return db.openObjectForWrite<AcDbLayerTableRecord>(layer.objectId)
  }

  const runLayerEdit = (
    db: AcDbDatabase | undefined,
    fn: () => boolean
  ): boolean => {
    if (!db) return false
    let result = false
    acapRunDatabaseEdit(db, layerEditLabel, () => {
      result = fn()
    })
    return result
  }

  const setLayerFrozenState = (
    layer: AcDbLayerTableRecord,
    frozen: boolean
  ) => {
    const flags = layer.standardFlags ?? 0
    layer.standardFlags = frozen
      ? flags | layerFrozenFlag
      : flags & ~layerFrozenFlag
  }

  const setLayerLockedState = (
    layer: AcDbLayerTableRecord,
    locked: boolean
  ) => {
    const flags = layer.standardFlags ?? 0
    layer.standardFlags = locked
      ? flags | layerLockedFlag
      : flags & ~layerLockedFlag
  }

  const toLayerInfo = (layer: AcDbLayerTableRecord): LayerInfo => ({
    name: layer.name,
    color: layer.color.toString(),
    cssColor: layer.color.cssColor || '#FFFFFF',
    isLocked: layer.isLocked,
    isFrozen: layer.isFrozen,
    isInUse: layer.isInUse,
    isOn: !layer.isOff,
    isPlottable: layer.isPlottable,
    transparency: layer.transparency.toString(),
    linetype: layer.linetype,
    lineWeight: layer.lineWeight
  })

  const reset = (db?: AcDbDatabase) => {
    reactiveLayers.length = 0
    if (!db) return

    for (const layer of db.tables.layerTable.newIterator()) {
      reactiveLayers.push(toLayerInfo(layer))
    }
  }

  const findLayerInfo = (name: string) =>
    reactiveLayers.find(layer => layer.name === name)

  const upsertLayerInfo = (layer: AcDbLayerTableRecord) => {
    const info = findLayerInfo(layer.name)
    const nextInfo = toLayerInfo(layer)
    if (!info) {
      reactiveLayers.push(nextInfo)
      return
    }
    Object.assign(info, nextInfo)
  }

  const handleLayerAppended = (args: AcDbLayerEventArgs) => {
    upsertLayerInfo(args.layer)
  }

  const handleLayerModified = (args: AcDbLayerModifiedEventArgs) => {
    const info = findLayerInfo(args.layer.name)
    if (!info) {
      upsertLayerInfo(args.layer)
      return
    }
    Object.assign(info, toLayerInfo(args.layer))
  }

  const bindDatabase = (db?: AcDbDatabase) => {
    if (observedDatabase === db) return

    if (observedDatabase) {
      observedDatabase.events.layerAppended.removeEventListener(
        handleLayerAppended
      )
      observedDatabase.events.layerModified.removeEventListener(
        handleLayerModified
      )
    }

    observedDatabase = db
    reset(observedDatabase)
    syncCurrentLayerName(observedDatabase)

    if (!observedDatabase) return
    observedDatabase.events.layerAppended.addEventListener(handleLayerAppended)
    observedDatabase.events.layerModified.addEventListener(handleLayerModified)
  }

  const handleDocumentActivated = (args: AcDbDocumentEventArgs) => {
    bindDatabase(args.doc.database)
  }

  const handleSysVarChanged = (args: AcDbSysVarEventArgs) => {
    if (args.database !== observedDatabase) return
    if (args.name.toUpperCase() !== 'CLAYER') return
    syncCurrentLayerName(args.database)
  }

  /**
   * =========================================================
   * Current layer (source of truth: database.clayer)
   * =========================================================
   */
  const currentLayerName = computed<string>({
    get: () => currentLayerNameState.value,
    set: name => {
      setCurrentLayer(name)
    }
  })

  const currentLayerInfo = computed<LayerInfo | undefined>(() =>
    reactiveLayers.find(l => l.name === currentLayerName.value)
  )

  /**
   * =========================================================
   * Mutations
   * =========================================================
   */
  function switchCurrentLayerIfNeeded(
    db: AcDbDatabase,
    targetLayerName: string
  ) {
    if (db.clayer !== targetLayerName) return true

    let fallbackLayerName: string | undefined
    let preferredLayerName: string | undefined

    for (const layer of db.tables.layerTable.newIterator()) {
      if (layer.name === targetLayerName) continue
      fallbackLayerName ??= layer.name
      if (!layer.isOff && !layer.isFrozen) {
        preferredLayerName = layer.name
        break
      }
    }

    const nextLayerName = preferredLayerName ?? fallbackLayerName
    if (!nextLayerName) return false

    const nextCurrentLayer = openLayerForWrite(db, nextLayerName)
    if (!nextCurrentLayer) return false

    nextCurrentLayer.isOff = false
    setLayerFrozenState(nextCurrentLayer, false)
    db.clayer = nextCurrentLayer.name
    syncCurrentLayerName(db)
    return true
  }

  function setCurrentLayer(layerName: string) {
    const db = getCurrentDatabase()
    if (!db || !layerName) return false
    if (!db.tables.layerTable.getAt(layerName)) return false

    return runLayerEdit(db, () => {
      const layer = openLayerForWrite(db, layerName)
      if (!layer) return false

      layer.isOff = false
      setLayerFrozenState(layer, false)
      db.clayer = layer.name
      syncCurrentLayerName(db)
      return true
    })
  }

  function setLayerOn(layerName: string, isOn: boolean) {
    const db = getCurrentDatabase()
    if (!db || !layerName) return false
    if (!db.tables.layerTable.getAt(layerName)) return false

    return runLayerEdit(db, () => {
      if (!isOn && !switchCurrentLayerIfNeeded(db, layerName)) return false

      const layer = openLayerForWrite(db, layerName)
      if (!layer) return false

      layer.isOff = !isOn
      return true
    })
  }

  function toggleLayerOn(layerName: string) {
    const db = getCurrentDatabase()
    if (!db || !layerName) return false
    const layer = db.tables.layerTable.getAt(layerName)
    if (!layer) return false
    return setLayerOn(layer.name, layer.isOff)
  }

  function setLayerFrozen(layerName: string, isFrozen: boolean) {
    const db = getCurrentDatabase()
    if (!db || !layerName) return false
    if (!db.tables.layerTable.getAt(layerName)) return false

    return runLayerEdit(db, () => {
      if (isFrozen && !switchCurrentLayerIfNeeded(db, layerName)) return false

      const layer = openLayerForWrite(db, layerName)
      if (!layer) return false

      setLayerFrozenState(layer, isFrozen)
      return true
    })
  }

  function toggleLayerFrozen(layerName: string) {
    const db = getCurrentDatabase()
    if (!db || !layerName) return false
    const layer = db.tables.layerTable.getAt(layerName)
    if (!layer) return false
    return setLayerFrozen(layer.name, !layer.isFrozen)
  }

  function setLayerLocked(layerName: string, isLocked: boolean) {
    const db = getCurrentDatabase()
    if (!db || !layerName) return false
    if (!db.tables.layerTable.getAt(layerName)) return false

    return runLayerEdit(db, () => {
      const layer = openLayerForWrite(db, layerName)
      if (!layer) return false

      setLayerLockedState(layer, isLocked)
      return true
    })
  }

  function toggleLayerLocked(layerName: string) {
    const db = getCurrentDatabase()
    if (!db || !layerName) return false
    const layer = db.tables.layerTable.getAt(layerName)
    if (!layer) return false
    return setLayerLocked(layer.name, !layer.isLocked)
  }

  function toggleLayerState(layerName: string, state: LayerStateToggleKey) {
    switch (state) {
      case 'on':
        return toggleLayerOn(layerName)
      case 'frozen':
        return toggleLayerFrozen(layerName)
      case 'locked':
        return toggleLayerLocked(layerName)
      default:
        return false
    }
  }

  function isolateLayer(layerName: string) {
    const db = getCurrentDatabase()
    if (!db || !layerName) return false
    if (!db.tables.layerTable.getAt(layerName)) return false

    return runLayerEdit(db, () => {
      for (const layer of db.tables.layerTable.newIterator()) {
        const keepVisible = layer.name === layerName
        const opened = openLayerForWrite(db, layer.name)
        if (!opened) continue

        opened.isOff = !keepVisible
        if (keepVisible) {
          setLayerFrozenState(opened, false)
        }
      }

      db.clayer = layerName
      syncCurrentLayerName(db)
      return true
    })
  }

  function setAllLayersOn() {
    const db = getCurrentDatabase()
    if (!db) return false

    return runLayerEdit(db, () => {
      let changed = false
      for (const layer of db.tables.layerTable.newIterator()) {
        if (!layer.isOff) continue

        const opened = openLayerForWrite(db, layer.name)
        if (!opened) continue

        opened.isOff = false
        changed = true
      }

      return changed
    })
  }

  function setLayerColor(layerName: string, color: AcCmColor) {
    const db = getCurrentDatabase()
    if (!db) return false
    if (!db.tables.layerTable.getAt(layerName)) return false

    return runLayerEdit(db, () => {
      const layer = openLayerForWrite(db, layerName)
      if (!layer) return false

      layer.color = color
      return true
    })
  }

  function setLayerLineWeight(layerName: string, lineWeight: number) {
    const db = getCurrentDatabase()
    if (!db) return false
    if (!db.tables.layerTable.getAt(layerName)) return false

    return runLayerEdit(db, () => {
      const layer = openLayerForWrite(db, layerName)
      if (!layer) return false

      layer.lineWeight = lineWeight
      return true
    })
  }

  function captureLayerSnapshot(
    db = getCurrentDatabase()
  ): LayerStateSnapshot | null {
    if (!db) return null
    return {
      clayer: db.clayer,
      states: [...db.tables.layerTable.newIterator()].map(toLayerInfo)
    }
  }

  function applyLayerSnapshot(
    snapshot: LayerStateSnapshot,
    db = getCurrentDatabase()
  ) {
    if (!db) return false

    return runLayerEdit(db, () => {
      snapshot.states.forEach(state => {
        const layer = openLayerForWrite(db, state.name)
        if (!layer) return

        layer.isOff = !state.isOn
        setLayerFrozenState(layer, state.isFrozen)
        setLayerLockedState(layer, state.isLocked)
      })

      const currentLayer = openLayerForWrite(db, snapshot.clayer)
      if (currentLayer) {
        currentLayer.isOff = false
        setLayerFrozenState(currentLayer, false)
        db.clayer = currentLayer.name
        syncCurrentLayerName(db)
        return true
      }

      syncCurrentLayerName(db)
      return false
    })
  }

  editor.events.documentActivated.addEventListener(handleDocumentActivated)
  AcDbSysVarManager.instance().events.sysVarChanged.addEventListener(
    handleSysVarChanged
  )
  bindDatabase(getCurrentDatabase())

  onScopeDispose(() => {
    editor.events.documentActivated.removeEventListener(handleDocumentActivated)
    AcDbSysVarManager.instance().events.sysVarChanged.removeEventListener(
      handleSysVarChanged
    )
    bindDatabase(undefined)
  })

  return {
    layers: reactiveLayers,
    currentLayerName,
    currentLayerInfo,
    setCurrentLayer,
    setLayerOn,
    setLayerFrozen,
    setLayerLocked,
    toggleLayerOn,
    toggleLayerFrozen,
    toggleLayerLocked,
    toggleLayerState,
    isolateLayer,
    setAllLayersOn,
    captureLayerSnapshot,
    applyLayerSnapshot,
    setLayerColor,
    setLayerLineWeight
  }
}
