import { AcApDocManager } from '@mlightcad/cad-simple-viewer'
import { AcCmColor, AcDbDatabase } from '@mlightcad/data-model'
import { computed, reactive } from 'vue'

export interface LayerInfo {
  name: string
  /**
   * Color string generated by AcCmColor.toString()
   */
  color: string
  cssColor: string
  isLocked: boolean
  isHidden: boolean
  isInUse: boolean
  isOn: boolean
  isPlottable: boolean
  transparency: string
  linetype: string
  lineWeight: number
}

export function useLayers(editor: AcApDocManager) {
  const reactiveLayers = reactive<LayerInfo[]>([])
  const doc = editor.curDocument

  /**
   * =========================================================
   * Current layer (source of truth: database.clayer)
   * =========================================================
   */
  const currentLayerName = computed<string>({
    get: () => doc.database.clayer,
    set: name => {
      doc.database.clayer = name
    }
  })

  const currentLayerInfo = computed<LayerInfo | undefined>(() =>
    reactiveLayers.find(l => l.name === currentLayerName.value)
  )

  /**
   * =========================================================
   * Init / reset
   * =========================================================
   */
  const reset = (db: AcDbDatabase) => {
    const it = db.tables.layerTable.newIterator()
    for (const layer of it) {
      reactiveLayers.push({
        name: layer.name,
        color: layer.color.toString(),
        cssColor: layer.color.cssColor || '#FFFFFF',
        isLocked: layer.isLocked,
        isHidden: layer.isHidden,
        isInUse: layer.isInUse,
        isOn: !layer.isOff,
        isPlottable: layer.isPlottable,
        transparency: layer.transparency.toString(),
        linetype: layer.linetype,
        lineWeight: layer.lineWeight
      })
    }
  }

  reset(doc.database)

  /**
   * =========================================================
   * Event sync
   * =========================================================
   */
  doc.database.events.layerModified.addEventListener(args => {
    const layer = reactiveLayers.find(l => l.name === args.layer.name)
    if (!layer) return

    const c = args.changes
    if (c.color) {
      layer.color = c.color.toString()
      layer.cssColor = c.color.cssColor || '#FFFFFF'
    }
    if (c.isLocked != null) layer.isLocked = c.isLocked
    if (c.isHidden != null) layer.isHidden = c.isHidden
    if (c.isInUse != null) layer.isInUse = c.isInUse
    if (c.isOff != null) layer.isOn = !c.isOff
    if (c.isPlottable != null) layer.isPlottable = c.isPlottable
    if (c.transparency) layer.transparency = c.transparency.toString()
    if (c.linetype) layer.linetype = c.linetype
    if (c.lineWeight != null) layer.lineWeight = c.lineWeight
  })

  editor.events.documentActivated.addEventListener(args => {
    reactiveLayers.length = 0
    reset(args.doc.database)
  })

  /**
   * =========================================================
   * Mutations
   * =========================================================
   */
  function setLayerColor(layerName: string, colorIndex: number) {
    const dbLayer = doc.database.tables.layerTable.getAt(layerName)
    if (!dbLayer) return

    const color = new AcCmColor()
    color.colorIndex = colorIndex
    dbLayer.color = color
  }

  function setLayerLineWeight(layerName: string, lineWeight: number) {
    const dbLayer = doc.database.tables.layerTable.getAt(layerName)
    if (!dbLayer) return
    dbLayer.lineWeight = lineWeight
  }

  return {
    layers: reactiveLayers,
    currentLayerName,
    currentLayerInfo,
    setLayerColor,
    setLayerLineWeight
  }
}
