import { defineConfig } from 'vitepress'

const base = process.env.DOCS_BASE || '/cad-viewer/docs/'

function guideSidebar(prefix: string, labels: Record<string, string>) {
  return [
    {
      text: labels.guide,
      items: [
        { text: labels.ui, link: `${prefix}/guide/ui` },
        {
          text: labels.gesturesGroup,
          collapsed: false,
          items: [
            { text: labels.gestures, link: `${prefix}/guide/gestures` },
            { text: labels.simmouse, link: `${prefix}/guide/simulated-mouse` },
            { text: labels.aids, link: `${prefix}/guide/aids` },
          ],
        },
      ],
    },
    {
      text: labels.markupGroup,
      collapsed: false,
      items: [
        { text: labels.mkOverview, link: `${prefix}/guide/markup/overview` },
        { text: labels.mkArrow, link: `${prefix}/guide/markup/arrow` },
        { text: labels.mkText, link: `${prefix}/guide/markup/text` },
        { text: labels.mkCloud, link: `${prefix}/guide/markup/cloud` },
        { text: labels.mkRect, link: `${prefix}/guide/markup/rectangle` },
        { text: labels.mkCircle, link: `${prefix}/guide/markup/circle` },
        { text: labels.mkCallout, link: `${prefix}/guide/markup/callout` },
        { text: labels.mkResults, link: `${prefix}/guide/markup/results` },
      ],
    },
    {
      text: labels.measureGroup,
      collapsed: false,
      items: [
        { text: labels.msOverview, link: `${prefix}/guide/measure/overview` },
        { text: labels.msDistance, link: `${prefix}/guide/measure/distance` },
        { text: labels.msContinuous, link: `${prefix}/guide/measure/distance-continuous` },
        { text: labels.msArea, link: `${prefix}/guide/measure/area` },
        { text: labels.msCoords, link: `${prefix}/guide/measure/coordinates` },
        { text: labels.msArc, link: `${prefix}/guide/measure/arc-length` },
        { text: labels.msAngle, link: `${prefix}/guide/measure/angle` },
        { text: labels.msResults, link: `${prefix}/guide/measure/results` },
      ],
    },
  ]
}

export default defineConfig({
  title: 'MLightCAD Viewer',
  description: 'Web-based CAD Viewer',
  base,
  head: [['link', { rel: 'icon', type: 'image/svg+xml', href: `${base}logo.svg` }]],
  ignoreDeadLinks: true,
  locales: {
    root: {
      lang: 'en-US',
      label: 'English',
      themeConfig: {
        nav: [
          { text: 'Guide', link: '/guide/ui' },
          { text: 'API', link: '/api/' },
          { text: 'GitHub', link: 'https://github.com/mlightcad/cad-viewer' },
        ],
        sidebar: guideSidebar('', {
          guide: 'Guide',
          ui: 'User Interface',
          gesturesGroup: 'Gestures and Aids',
          gestures: 'Gestures',
          simmouse: 'Simulated Mouse',
          aids: 'Drawing Aids',
          markupGroup: 'Markup',
          mkOverview: 'Markup Overview',
          mkArrow: 'Arrow',
          mkText: 'Text',
          mkCloud: 'Revision Cloud',
          mkRect: 'Rectangle',
          mkCircle: 'Circle',
          mkCallout: 'Callout',
          mkResults: 'View Results',
          measureGroup: 'Measurement',
          msOverview: 'Measurement Overview',
          msDistance: 'Distance',
          msContinuous: 'Continuous Distance',
          msArea: 'Area',
          msCoords: 'Coordinates',
          msArc: 'Arc Length',
          msAngle: 'Angle',
          msResults: 'View Results',
        }),
      },
    },
    zh: {
      lang: 'zh-CN',
      label: '中文',
      themeConfig: {
        nav: [
          { text: '指南', link: '/zh/guide/ui' },
          { text: 'API', link: '/api/' },
          { text: 'GitHub', link: 'https://github.com/mlightcad/cad-viewer' },
        ],
        sidebar: guideSidebar('/zh', {
          guide: '指南',
          ui: '用户界面',
          gesturesGroup: '手势和辅助显示',
          gestures: '手势',
          simmouse: '模拟鼠标',
          aids: '辅助显示',
          markupGroup: '批注',
          mkOverview: '批注功能说明',
          mkArrow: '箭头',
          mkText: '文字',
          mkCloud: '云线',
          mkRect: '矩形',
          mkCircle: '圆',
          mkCallout: '标注（Callout）',
          mkResults: '看结果',
          measureGroup: '测量',
          msOverview: '测量功能说明',
          msDistance: '测长度',
          msContinuous: '连续测',
          msArea: '测面积',
          msCoords: '测坐标',
          msArc: '测弧长',
          msAngle: '测角度',
          msResults: '看结果',
        }),
      },
    },
    ar: {
      lang: 'ar-SA',
      label: 'العربية',
      dir: 'rtl',
      themeConfig: {
        nav: [
          { text: 'الدليل', link: '/ar/guide/ui' },
          { text: 'API', link: '/api/' },
          { text: 'GitHub', link: 'https://github.com/mlightcad/cad-viewer' },
        ],
        sidebar: guideSidebar('/ar', {
          guide: 'الدليل',
          ui: 'واجهة المستخدم',
          gesturesGroup: 'الإيماءات والمساعدات',
          gestures: 'الإيماءات',
          simmouse: 'الماوس المحاكى',
          aids: 'وسائل المساعدة',
          markupGroup: 'التعليقات',
          mkOverview: 'نظرة عامة على التعليقات',
          mkArrow: 'سهم',
          mkText: 'نص',
          mkCloud: 'سحابة مراجعة',
          mkRect: 'مستطيل',
          mkCircle: 'دائرة',
          mkCallout: 'تعليق توضيحي (Callout)',
          mkResults: 'عرض النتائج',
          measureGroup: 'القياس',
          msOverview: 'نظرة عامة على القياس',
          msDistance: 'قياس الطول',
          msContinuous: 'قياس متتابع',
          msArea: 'قياس المساحة',
          msCoords: 'قياس الإحداثيات',
          msArc: 'قياس طول القوس',
          msAngle: 'قياس الزاوية',
          msResults: 'عرض النتائج',
        }),
      },
    },
    cs: {
      lang: 'cs-CZ',
      label: 'Čeština',
      themeConfig: {
        nav: [
          { text: 'Průvodce', link: '/cs/guide/ui' },
          { text: 'API', link: '/api/' },
          { text: 'GitHub', link: 'https://github.com/mlightcad/cad-viewer' },
        ],
        sidebar: guideSidebar('/cs', {
          guide: 'Průvodce',
          ui: 'Uživatelské rozhraní',
          gesturesGroup: 'Gesta a pomůcky',
          gestures: 'Gesta',
          simmouse: 'Simulovaná myš',
          aids: 'Kreslicí pomůcky',
          markupGroup: 'Komentáře',
          mkOverview: 'Přehled komentářů',
          mkArrow: 'Šipka',
          mkText: 'Text',
          mkCloud: 'Revizní oblak',
          mkRect: 'Obdélník',
          mkCircle: 'Kružnice',
          mkCallout: 'Bublina (Callout)',
          mkResults: 'Zobrazení výsledků',
          measureGroup: 'Měření',
          msOverview: 'Přehled měření',
          msDistance: 'Měření vzdálenosti',
          msContinuous: 'Postupné měření',
          msArea: 'Měření plochy',
          msCoords: 'Měření souřadnic',
          msArc: 'Měření délky oblouku',
          msAngle: 'Měření úhlu',
          msResults: 'Zobrazení výsledků',
        }),
      },
    },
    tr: {
      lang: 'tr-TR',
      label: 'Türkçe',
      themeConfig: {
        nav: [
          { text: 'Rehber', link: '/tr/guide/ui' },
          { text: 'API', link: '/api/' },
          { text: 'GitHub', link: 'https://github.com/mlightcad/cad-viewer' },
        ],
        sidebar: guideSidebar('/tr', {
          guide: 'Rehber',
          ui: 'Kullanıcı Arayüzü',
          gesturesGroup: 'Hareketler ve Yardımcılar',
          gestures: 'Hareketler',
          simmouse: 'Sanal Fare',
          aids: 'Çizim Yardımcıları',
          markupGroup: 'Açıklamalar',
          mkOverview: 'Açıklama Genel Bakış',
          mkArrow: 'Ok',
          mkText: 'Metin',
          mkCloud: 'Revizyon Bulutu',
          mkRect: 'Dikdörtgen',
          mkCircle: 'Daire',
          mkCallout: 'Balon Açıklama (Callout)',
          mkResults: 'Sonuçları Görüntüle',
          measureGroup: 'Ölçüm',
          msOverview: 'Ölçüm Genel Bakış',
          msDistance: 'Uzunluk Ölçümü',
          msContinuous: 'Ardışık Ölçüm',
          msArea: 'Alan Ölçümü',
          msCoords: 'Koordinat Ölçümü',
          msArc: 'Yay Uzunluğu Ölçümü',
          msAngle: 'Açı Ölçümü',
          msResults: 'Sonuçları Görüntüle',
        }),
      },
    },
  },
})
