jest.mock('@mlightcad/cad-simple-viewer', () => ({
  ML_UI_MOBILE_MAX_WIDTH: 768
}))

import { buildAcExHtmlShellBody } from '../src/AcExHtmlShell'

describe('buildAcExHtmlShellBody', () => {
  it('omits measurement toolbar controls in view mode', () => {
    const html = buildAcExHtmlShellBody('#000000', 'view')

    expect(html).toContain('data-action="select"')
    expect(html).toContain('data-action="pan"')
    expect(html).toContain('id="mlcad-zoom-menu-btn"')
    expect(html).toContain('id="mlcad-zoom-strip-wrap"')
    expect(html).toContain('data-action="fit"')
    expect(html).toContain('data-action="zoom-window"')
    expect(html).toContain('data-action="zoom-original"')
    expect(html).toContain('id="mlcad-layers-btn"')
    expect(html).toContain('id="mlcad-layout-menu-btn"')
    expect(html).toContain('id="mlcad-lang-btn"')
    expect(html).toContain('id="mlcad-lang-badge"')
    expect(html).toContain('id="mlcad-locale-strip-wrap"')
    expect(html).not.toContain('data-measure-mode=')
    expect(html).not.toContain('id="mlcad-measure-menu-btn"')
    expect(html).not.toContain('id="mlcad-markup-menu-btn"')
    expect(html).not.toContain('id="mlcad-snap-menu-btn"')
    expect(html).not.toContain('id="mlcad-settings-btn"')
    expect(html).not.toContain('id="mlcad-settings-wrap"')
    expect(html).not.toContain('id="mlcad-snap-strip-wrap"')
    expect(html).not.toContain('mlcad-tool-separator')
    expect(html).toContain('id="mlcad-status-bar"')
  })

  it('uses Measurement / Review / Snap / Language parent strips in measure mode', () => {
    const html = buildAcExHtmlShellBody('#000000', 'measure')

    expect(html).toContain('data-action="select"')
    expect(html).toContain('data-action="pan"')
    expect(html).toContain('id="mlcad-zoom-menu-btn"')
    expect(html).toContain('data-action="zoom-original"')
    expect(html).toContain('id="mlcad-measure-menu-btn"')
    expect(html).toContain('id="mlcad-markup-menu-btn"')
    expect(html).toContain('id="mlcad-snap-menu-btn"')
    expect(html).toContain('id="mlcad-layout-menu-btn"')
    expect(html).toContain('id="mlcad-lang-btn"')
    expect(html).toContain('id="mlcad-lang-badge"')
    expect(html).toContain('has-children')
    expect(html).toContain('id="mlcad-measure-strip-wrap"')
    expect(html).toContain('id="mlcad-markup-strip-wrap"')
    expect(html).toContain('id="mlcad-snap-strip-wrap"')
    expect(html).toContain('id="mlcad-locale-strip-wrap"')
    expect(html).not.toContain('id="mlcad-settings-btn"')
    expect(html).not.toContain('id="mlcad-settings-wrap"')
    expect(html).not.toContain('mlcad-measure-submenu-template')
    expect(html).not.toContain('mlcad-markup-submenu-template')
    expect(html).toContain('data-measure-mode="distance"')
    expect(html).toContain('data-action="measure-import"')
    expect(html).toContain('data-markup-mode="cloud"')
    expect(html).toContain('data-action="markup-panel"')
    expect(html).toContain('id="mlcad-review-drawer"')
    expect(html.indexOf('id="mlcad-markup-strip-wrap"')).toBeLessThan(
      html.indexOf('id="mlcad-review-drawer"')
    )
    expect(html).toContain('mlcad-review-detail-close')
    expect(html).toContain('data-action="clear-markups"')
    expect(html).toContain('id="mlcad-status-bar"')
    expect(html.match(/mlcad-tool-separator/g)?.length).toBeGreaterThanOrEqual(2)
    // Child tools live in strips, not as first-level toolbar buttons.
    const toolbarHtml = html.match(/<nav id="mlcad-toolbar"[\s\S]*?<\/nav>/)?.[0]
    expect(toolbarHtml).toBeTruthy()
    expect(toolbarHtml).not.toContain('data-measure-mode')
    expect(toolbarHtml).not.toContain('data-markup-mode')
    expect(toolbarHtml).not.toContain('data-action="fit"')
    expect(toolbarHtml).not.toContain('data-action="zoom-window"')
    expect(toolbarHtml).not.toContain('data-action="zoom-original"')
    expect(toolbarHtml).toContain('title="Zoom"')
    expect(toolbarHtml).toContain('title="Object snap"')
    expect(toolbarHtml).toContain('title="Language"')
    expect(toolbarHtml).toContain('title="Layout"')
    expect(toolbarHtml).toContain('data-children-ui="sticky-toolbar"')
    expect(toolbarHtml).toContain('data-children-ui="toolbar"')
    expect(toolbarHtml).toContain('data-children-ui="menu"')
  })

  it('omits markup toolbar controls in view mode', () => {
    const html = buildAcExHtmlShellBody('#000000', 'view')
    expect(html).not.toContain('data-markup-mode=')
    expect(html).not.toContain('data-action="clear-markups"')
    expect(html).not.toContain('data-action="markup-panel"')
    expect(html).not.toContain('id="mlcad-review-drawer"')
  })

  it('omits the layout switcher when layouts are not exported', () => {
    const html = buildAcExHtmlShellBody('#000000', 'measure', false)

    expect(html).toContain('id="mlcad-layers-btn"')
    expect(html).not.toContain('id="mlcad-layout-menu-btn"')
    expect(html).not.toContain('title="Layout"')
  })
})
